"""GivEnergy hybrid inverter sensor definitions.

Credit: cdpuk/givenergy-local (https://github.com/cdpuk/givenergy-local)

Register map sourced from:
  cdpuk/givenergy-local:custom_components/givenergy_local/givenergy_modbus/model/inverter.py
  cdpuk/givenergy-local:custom_components/givenergy_local/givenergy_modbus/model/battery.py

GivEnergy inverters use Modbus TCP on port 8899.
- Input registers (IR) contain live read-only data.
- Holding registers (HR) contain both live data and writable settings.

Scale conventions from upstream:
  deci  = ÷10   (multiplier 0.1)
  centi = ÷100  (multiplier 0.01)
  milli = ÷1000 (multiplier 0.001)
  Negative multiplier used for signed values (data_type S16).
"""

from homeassistant.components.sensor.const import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

from custom_components.hh_modbus_control.data.enums import Category, DataType, PollSpeed

# ---------------------------------------------------------------------------
# INPUT REGISTER GROUPS (IR — read-only live data)
# ---------------------------------------------------------------------------

givenergy_input_sensors = [
    # -------------------------------------------------------------------------
    # Group: Live Power Data (IR 0–59)
    # -------------------------------------------------------------------------
    {
        "register_start": 0,
        "poll_speed": PollSpeed.FAST,
        "register_type": "input",
        "entities": [
            {
                "name": "Inverter Status",
                "unique": "givenergy_inverter_status",
                "category": Category.STATUS_INFORMATION,
                "register": ["0"],
                "multiplier": 0,
            },
            {
                "name": "PV1 Voltage",
                "unique": "givenergy_pv1_voltage",
                "category": Category.PV_INFORMATION,
                "register": ["1"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Voltage",
                "unique": "givenergy_pv2_voltage",
                "category": Category.PV_INFORMATION,
                "register": ["2"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "DC Bus Positive Voltage",
                "unique": "givenergy_dc_bus_positive",
                "category": Category.DEVICE_INTERNAL_DATA,
                "register": ["3"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "hidden": True,
            },
            {
                "name": "DC Bus Negative Voltage",
                "unique": "givenergy_dc_bus_negative",
                "category": Category.DEVICE_INTERNAL_DATA,
                "register": ["4"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "hidden": True,
            },
            {
                "name": "AC Voltage",
                "unique": "givenergy_ac_voltage",
                "category": Category.AC_INFORMATION,
                "register": ["5"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            # IR 6-7: Battery throughput total (U32 deci kWh)
            {
                "name": "Battery Throughput Total",
                "unique": "givenergy_battery_throughput_total",
                "category": Category.BATTERY_INFORMATION,
                "register": ["6", "7"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "PV1 Current",
                "unique": "givenergy_pv1_current",
                "category": Category.PV_INFORMATION,
                "register": ["8"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Current",
                "unique": "givenergy_pv2_current",
                "category": Category.PV_INFORMATION,
                "register": ["9"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "AC Current",
                "unique": "givenergy_ac_current",
                "category": Category.AC_INFORMATION,
                "register": ["10"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            # IR 11-12: PV total energy (U32 deci kWh)
            {
                "name": "PV Total Energy",
                "unique": "givenergy_pv_total_energy",
                "category": Category.PV_INFORMATION,
                "register": ["11", "12"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "AC Frequency",
                "unique": "givenergy_ac_frequency",
                "category": Category.AC_INFORMATION,
                "register": ["13"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            # IR 14-16: padding/reserve
            {
                "name": "reserve_14",
                "unique": "givenergy_reserve_14",
                "register": ["14"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_15",
                "unique": "givenergy_reserve_15",
                "register": ["15"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_16",
                "unique": "givenergy_reserve_16",
                "register": ["16"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "PV1 Today Energy",
                "unique": "givenergy_pv1_today_energy",
                "category": Category.PV_INFORMATION,
                "register": ["17"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "PV1 Power",
                "unique": "givenergy_pv1_power",
                "category": Category.PV_INFORMATION,
                "register": ["18"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Today Energy",
                "unique": "givenergy_pv2_today_energy",
                "category": Category.PV_INFORMATION,
                "register": ["19"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "PV2 Power",
                "unique": "givenergy_pv2_power",
                "category": Category.PV_INFORMATION,
                "register": ["20"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            # IR 21-22: Grid Export Total (U32 deci kWh)
            {
                "name": "Grid Export Total",
                "unique": "givenergy_grid_export_total",
                "category": Category.ENERGY_DATA,
                "register": ["21", "22"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve_23",
                "unique": "givenergy_reserve_23",
                "register": ["23"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "AC Output Power",
                "unique": "givenergy_ac_output_power",
                "category": Category.AC_INFORMATION,
                "register": ["24"],
                "multiplier": 1,
                "data_type": DataType.S16.value,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid Export Today",
                "unique": "givenergy_grid_export_today",
                "category": Category.ENERGY_DATA,
                "register": ["25"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Grid Import Today",
                "unique": "givenergy_grid_import_today",
                "category": Category.ENERGY_DATA,
                "register": ["26"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            # IR 27-28: Inverter In Total (U32 deci kWh)
            {
                "name": "Inverter In Total",
                "unique": "givenergy_inverter_in_total",
                "category": Category.ENERGY_DATA,
                "register": ["27", "28"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve_29",
                "unique": "givenergy_reserve_29",
                "register": ["29"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid Power",
                "unique": "givenergy_grid_power",
                "category": Category.GRID_CODE_INFORMATION,
                "register": ["30"],
                "multiplier": 1,
                "data_type": DataType.S16.value,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "EPS Backup Power",
                "unique": "givenergy_eps_backup_power",
                "category": Category.AC_INFORMATION,
                "register": ["31"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            # IR 32-33: Grid Import Total (U32 deci kWh)
            {
                "name": "Grid Import Total",
                "unique": "givenergy_grid_import_total",
                "category": Category.ENERGY_DATA,
                "register": ["32", "33"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve_34",
                "unique": "givenergy_reserve_34",
                "register": ["34"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter In Today",
                "unique": "givenergy_inverter_in_today",
                "category": Category.ENERGY_DATA,
                "register": ["35"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Battery Charge Today",
                "unique": "givenergy_battery_charge_today",
                "category": Category.BATTERY_INFORMATION,
                "register": ["36"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Battery Discharge Today",
                "unique": "givenergy_battery_discharge_today",
                "category": Category.BATTERY_INFORMATION,
                "register": ["37"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve_38",
                "unique": "givenergy_reserve_38",
                "register": ["38"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_39",
                "unique": "givenergy_reserve_39",
                "register": ["39"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_40",
                "unique": "givenergy_reserve_40",
                "register": ["40"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter Heatsink Temperature",
                "unique": "givenergy_heatsink_temp",
                "category": Category.STATUS_INFORMATION,
                "register": ["41"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Load Demand",
                "unique": "givenergy_load_demand",
                "category": Category.LOAD_INFORMATION,
                "register": ["42"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve_43",
                "unique": "givenergy_reserve_43",
                "register": ["43"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter Out Today",
                "unique": "givenergy_inverter_out_today",
                "category": Category.ENERGY_DATA,
                "register": ["44"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            # IR 45-46: Inverter Out Total (U32 deci kWh)
            {
                "name": "Inverter Out Total",
                "unique": "givenergy_inverter_out_total",
                "category": Category.ENERGY_DATA,
                "register": ["45", "46"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve_47",
                "unique": "givenergy_reserve_47",
                "register": ["47"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_48",
                "unique": "givenergy_reserve_48",
                "register": ["48"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "System Mode",
                "unique": "givenergy_system_mode",
                "category": Category.STATUS_INFORMATION,
                "register": ["49"],
                "multiplier": 0,
            },
            {
                "name": "Battery Voltage",
                "unique": "givenergy_battery_voltage",
                "category": Category.BATTERY_INFORMATION,
                "register": ["50"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Current",
                "unique": "givenergy_battery_current",
                "category": Category.BATTERY_INFORMATION,
                "register": ["51"],
                "multiplier": 0.01,
                "data_type": DataType.S16.value,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Power",
                "unique": "givenergy_battery_power",
                "category": Category.BATTERY_INFORMATION,
                "register": ["52"],
                "multiplier": 1,
                "data_type": DataType.S16.value,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "EPS Backup Voltage",
                "unique": "givenergy_eps_voltage",
                "category": Category.AC_INFORMATION,
                "register": ["53"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "EPS Backup Frequency",
                "unique": "givenergy_eps_frequency",
                "category": Category.AC_INFORMATION,
                "register": ["54"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Charger Temperature",
                "unique": "givenergy_charger_temp",
                "category": Category.STATUS_INFORMATION,
                "register": ["55"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Temperature",
                "unique": "givenergy_battery_temp",
                "category": Category.BATTERY_INFORMATION,
                "register": ["56"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve_57",
                "unique": "givenergy_reserve_57",
                "register": ["57"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid Port Current",
                "unique": "givenergy_grid_port_current",
                "category": Category.GRID_CODE_INFORMATION,
                "register": ["58"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery SOC",
                "unique": "givenergy_battery_soc",
                "category": Category.BATTERY_INFORMATION,
                "register": ["59"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "device_class": SensorDeviceClass.BATTERY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },
]

# ---------------------------------------------------------------------------
# HOLDING REGISTER GROUPS (HR — device info read at startup)
# ---------------------------------------------------------------------------

givenergy_holding_sensors = [
    # -------------------------------------------------------------------------
    # Group: Device Info (HR 0–21, read once at startup)
    # -------------------------------------------------------------------------
    {
        "register_start": 0,
        "poll_speed": PollSpeed.ONCE,
        "register_type": "holding",
        "entities": [
            {
                "name": "Device Type Code",
                "unique": "givenergy_device_type_code",
                "category": Category.BASIC_INFORMATION,
                "register": ["0"],
                "multiplier": 0,
            },
            # HR 1-2: Module ID (U32 hex)
            {
                "name": "Module ID",
                "unique": "givenergy_module_id",
                "category": Category.BASIC_INFORMATION,
                "register": ["1", "2"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_3",
                "unique": "givenergy_hr_reserve_3",
                "register": ["3"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_4",
                "unique": "givenergy_hr_reserve_4",
                "register": ["4"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_5",
                "unique": "givenergy_hr_reserve_5",
                "register": ["5"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_6",
                "unique": "givenergy_hr_reserve_6",
                "register": ["6"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve_7",
                "unique": "givenergy_hr_reserve_7",
                "register": ["7"],
                "multiplier": 0,
                "hidden": True,
            },
            # HR 8-12: Battery Serial Number (5 registers = 10 ASCII chars)
            {
                "name": "Battery Serial Number",
                "unique": "givenergy_battery_serial_number",
                "category": Category.BASIC_INFORMATION,
                "register": ["8", "9", "10", "11", "12"],
                "multiplier": 0,
            },
            # HR 13-17: Inverter Serial Number (5 registers)
            {
                "name": "Serial Number",
                "unique": "givenergy_serial_number",
                "category": Category.BASIC_INFORMATION,
                "register": ["13", "14", "15", "16", "17"],
                "multiplier": 0,
            },
            {
                "name": "Battery BMS Firmware Version",
                "unique": "givenergy_bms_firmware_version",
                "category": Category.BASIC_INFORMATION,
                "register": ["18"],
                "multiplier": 0,
            },
            {
                "name": "DSP Firmware Version",
                "unique": "givenergy_dsp_firmware_version",
                "category": Category.BASIC_INFORMATION,
                "register": ["19"],
                "multiplier": 0,
            },
            {
                "name": "reserve_20",
                "unique": "givenergy_hr_reserve_20",
                "register": ["20"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "ARM Firmware Version",
                "unique": "givenergy_arm_firmware_version",
                "category": Category.BASIC_INFORMATION,
                "register": ["21"],
                "multiplier": 0,
            },
        ],
    },
]

# Combined list: all sensors (input + holding)
givenergy_sensors = givenergy_input_sensors + givenergy_holding_sensors
