"""Sun-Synk / Deye single-phase hybrid inverter sensor definitions.

Register groups translated from the sunsynk library (Other Addons/sunsynk/).
Input registers (read-only data) use register_type="input".
Holding registers (writable settings) use register_type="holding".

Each group must have strictly contiguous register addresses.
Gaps are filled with hidden "reserve" sensors.
"""

from homeassistant.components.sensor.const import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

from custom_components.hh_modbus_control.data.enums import Category, PollSpeed

# ---------------------------------------------------------------------------
# INPUT REGISTER GROUPS (read-only live data)
# ---------------------------------------------------------------------------

sunsynk_input_sensors = [
    # -------------------------------------------------------------------------
    # Group: Device Info (registers 0-7, read once)
    # 0: Device type, 1: reserve, 2: Protocol, 3-7: Serial
    # -------------------------------------------------------------------------
    {
        "register_start": 0,
        "poll_speed": PollSpeed.ONCE,
        "register_type": "input",
        "entities": [
            {
                "name": "Device Type",
                "unique": "sunsynk_device_type",
                "category": Category.BASIC_INFORMATION,
                "register": ["0"],
                "multiplier": 0,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_1",
                "register": ["1"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Protocol Version",
                "unique": "sunsynk_protocol_version",
                "category": Category.BASIC_INFORMATION,
                "register": ["2"],
                "multiplier": 0,
            },
            {
                "name": "Serial Number",
                "unique": "sunsynk_serial_number",
                "category": Category.BASIC_INFORMATION,
                "register": ["3", "4", "5", "6", "7"],
                "multiplier": 0,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Group: Status & Temperatures (registers 59-95)
    # 59: Overall state, 60-88: energy, 90-92: temps/SD, 93-95: temps
    # -------------------------------------------------------------------------
    {
        "register_start": 59,
        "poll_speed": PollSpeed.NORMAL,
        "register_type": "input",
        "entities": [
            {
                "name": "Overall State",
                "unique": "sunsynk_overall_state",
                "category": Category.STATUS_INFORMATION,
                "register": ["59"],
                "multiplier": 0,
            },
            {
                "name": "Day Active Energy",
                "unique": "sunsynk_day_active_energy",
                "category": Category.ENERGY_DATA,
                "register": ["60"],
                "multiplier": -0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Day Reactive Energy",
                "unique": "sunsynk_day_reactive_energy",
                "category": Category.ENERGY_DATA,
                "register": ["61"],
                "multiplier": -0.1,
                "unit_of_measurement": "kVarh",
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_62",
                "register": ["62"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Total Active Energy",
                "unique": "sunsynk_total_active_energy",
                "category": Category.ENERGY_DATA,
                "register": ["63", "64"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Month PV Energy",
                "unique": "sunsynk_month_pv_energy",
                "category": Category.ENERGY_DATA,
                "register": ["65"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Month Load Energy",
                "unique": "sunsynk_month_load_energy",
                "category": Category.ENERGY_DATA,
                "register": ["66"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Month Grid Energy",
                "unique": "sunsynk_month_grid_energy",
                "category": Category.ENERGY_DATA,
                "register": ["67"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Year PV Energy",
                "unique": "sunsynk_year_pv_energy",
                "category": Category.ENERGY_DATA,
                "register": ["68", "69"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Day Battery Charge",
                "unique": "sunsynk_day_battery_charge",
                "category": Category.ENERGY_DATA,
                "register": ["70"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Day Battery Discharge",
                "unique": "sunsynk_day_battery_discharge",
                "category": Category.ENERGY_DATA,
                "register": ["71"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Total Battery Charge",
                "unique": "sunsynk_total_battery_charge",
                "category": Category.ENERGY_DATA,
                "register": ["72", "73"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Total Battery Discharge",
                "unique": "sunsynk_total_battery_discharge",
                "category": Category.ENERGY_DATA,
                "register": ["74", "75"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Day Grid Import",
                "unique": "sunsynk_day_grid_import",
                "category": Category.ENERGY_DATA,
                "register": ["76"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Day Grid Export",
                "unique": "sunsynk_day_grid_export",
                "category": Category.ENERGY_DATA,
                "register": ["77"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Total Grid Import",
                "unique": "sunsynk_total_grid_import",
                "category": Category.ENERGY_DATA,
                "register": ["78", "80"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            # 79: Grid frequency — moved to electrical group but must pad here
            # We cannot skip: 79 is between 78 and 80. We include it as a filler
            # BUT since 78+80 is a 32-bit pair that skips 79, we separate them.
            # Grid frequency lives in the electrical group (150-196). Registers
            # 78 and 80 form a non-contiguous 32-bit pair. We split: 78 alone, 80 alone.
        ],
    },

    # -------------------------------------------------------------------------
    # Group: Grid frequency at 79 (isolated, between energy pair 78/80)
    # -------------------------------------------------------------------------
    {
        "register_start": 79,
        "poll_speed": PollSpeed.FAST,
        "register_type": "input",
        "entities": [
            {
                "name": "Grid Frequency",
                "unique": "sunsynk_grid_frequency",
                "category": Category.AC_INFORMATION,
                "register": ["79"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Group: More energy counters (registers 80-108)
    # -------------------------------------------------------------------------
    {
        "register_start": 80,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "input",
        "entities": [
            {
                "name": "Total Grid Import High",
                "unique": "sunsynk_total_grid_import_high",
                "category": Category.ENERGY_DATA,
                "register": ["80"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "hidden": True,
            },
            {
                "name": "Total Grid Export",
                "unique": "sunsynk_total_grid_export",
                "category": Category.ENERGY_DATA,
                "register": ["81", "82"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_83",
                "register": ["83"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Day Load Energy",
                "unique": "sunsynk_day_load_energy",
                "category": Category.ENERGY_DATA,
                "register": ["84"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Total Load Energy",
                "unique": "sunsynk_total_load_energy",
                "category": Category.ENERGY_DATA,
                "register": ["85", "86"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Year Load Energy",
                "unique": "sunsynk_year_load_energy",
                "category": Category.ENERGY_DATA,
                "register": ["87", "88"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_89",
                "register": ["89"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "DC Transformer Temperature",
                "unique": "sunsynk_dc_transformer_temperature",
                "category": Category.STATUS_INFORMATION,
                "register": ["90"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Radiator Temperature",
                "unique": "sunsynk_radiator_temperature",
                "category": Category.STATUS_INFORMATION,
                "register": ["91"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "SD Status",
                "unique": "sunsynk_sd_status",
                "category": Category.STATUS_INFORMATION,
                "register": ["92"],
                "multiplier": 0,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_93",
                "register": ["93"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_94",
                "register": ["94"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Environment Temperature",
                "unique": "sunsynk_environment_temperature",
                "category": Category.STATUS_INFORMATION,
                "register": ["95"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Total PV Energy",
                "unique": "sunsynk_total_pv_energy",
                "category": Category.ENERGY_DATA,
                "register": ["96", "97"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Year Grid Export",
                "unique": "sunsynk_year_grid_export",
                "category": Category.ENERGY_DATA,
                "register": ["98", "99"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_100",
                "register": ["100"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_101",
                "register": ["101"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_102",
                "register": ["102"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Fault 1",
                "unique": "sunsynk_fault_1",
                "category": Category.STATUS_INFORMATION,
                "register": ["103"],
                "multiplier": 0,
            },
            {
                "name": "Fault 2",
                "unique": "sunsynk_fault_2",
                "category": Category.STATUS_INFORMATION,
                "register": ["104"],
                "multiplier": 0,
            },
            {
                "name": "Fault 3",
                "unique": "sunsynk_fault_3",
                "category": Category.STATUS_INFORMATION,
                "register": ["105"],
                "multiplier": 0,
            },
            {
                "name": "Fault 4",
                "unique": "sunsynk_fault_4",
                "category": Category.STATUS_INFORMATION,
                "register": ["106"],
                "multiplier": 0,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_107",
                "register": ["107"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Day PV Energy",
                "unique": "sunsynk_day_pv_energy",
                "category": Category.ENERGY_DATA,
                "register": ["108"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Group: PV (registers 109-114, all contiguous)
    # -------------------------------------------------------------------------
    {
        "register_start": 109,
        "poll_speed": PollSpeed.FAST,
        "register_type": "input",
        "entities": [
            {
                "name": "PV1 Voltage",
                "unique": "sunsynk_pv1_voltage",
                "category": Category.PV_INFORMATION,
                "register": ["109"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV1 Current",
                "unique": "sunsynk_pv1_current",
                "category": Category.PV_INFORMATION,
                "register": ["110"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Voltage",
                "unique": "sunsynk_pv2_voltage",
                "category": Category.PV_INFORMATION,
                "register": ["111"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Current",
                "unique": "sunsynk_pv2_current",
                "category": Category.PV_INFORMATION,
                "register": ["112"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV3 Voltage",
                "unique": "sunsynk_pv3_voltage",
                "category": Category.PV_INFORMATION,
                "register": ["113"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV3 Current",
                "unique": "sunsynk_pv3_current",
                "category": Category.PV_INFORMATION,
                "register": ["114"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Group: Grid & Electrical (registers 150-196)
    # Filling gaps with reserve sensors
    # -------------------------------------------------------------------------
    {
        "register_start": 150,
        "poll_speed": PollSpeed.FAST,
        "register_type": "input",
        "entities": [
            {
                "name": "Grid Voltage",
                "unique": "sunsynk_grid_voltage",
                "category": Category.AC_INFORMATION,
                "register": ["150"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_151",
                "register": ["151"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_152",
                "register": ["152"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_153",
                "register": ["153"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter Voltage",
                "unique": "sunsynk_inverter_voltage",
                "category": Category.AC_INFORMATION,
                "register": ["154"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_155",
                "register": ["155"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_156",
                "register": ["156"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_157",
                "register": ["157"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_158",
                "register": ["158"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_159",
                "register": ["159"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid Current L1",
                "unique": "sunsynk_grid_current_l1",
                "category": Category.AC_INFORMATION,
                "register": ["160"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid Current L2",
                "unique": "sunsynk_grid_current_l2",
                "category": Category.AC_INFORMATION,
                "register": ["161"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_162",
                "register": ["162"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_163",
                "register": ["163"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter Current",
                "unique": "sunsynk_inverter_current",
                "category": Category.AC_INFORMATION,
                "register": ["164"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_165",
                "register": ["165"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "AUX Power",
                "unique": "sunsynk_aux_power",
                "category": Category.GENERATOR_INFORMATION,
                "register": ["166"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid LD Power",
                "unique": "sunsynk_grid_ld_power",
                "category": Category.AC_INFORMATION,
                "register": ["167"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid L2 Power",
                "unique": "sunsynk_grid_l2_power",
                "category": Category.AC_INFORMATION,
                "register": ["168"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid Power",
                "unique": "sunsynk_grid_power",
                "category": Category.AC_INFORMATION,
                "register": ["169"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_170",
                "register": ["170"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_171",
                "register": ["171"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid CT Power",
                "unique": "sunsynk_grid_ct_power",
                "category": Category.AC_INFORMATION,
                "register": ["172"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_173",
                "register": ["173"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_174",
                "register": ["174"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Inverter Power",
                "unique": "sunsynk_inverter_power",
                "category": Category.AC_INFORMATION,
                "register": ["175"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Load L1 Power",
                "unique": "sunsynk_load_l1_power",
                "category": Category.LOAD_INFORMATION,
                "register": ["176"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Load L2 Power",
                "unique": "sunsynk_load_l2_power",
                "category": Category.LOAD_INFORMATION,
                "register": ["177"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Load Power",
                "unique": "sunsynk_load_power",
                "category": Category.LOAD_INFORMATION,
                "register": ["178"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_179",
                "register": ["179"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_180",
                "register": ["180"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "AUX Voltage",
                "unique": "sunsynk_aux_voltage",
                "category": Category.GENERATOR_INFORMATION,
                "register": ["181"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Temperature",
                "unique": "sunsynk_battery_temperature",
                "category": Category.BATTERY_INFORMATION,
                "register": ["182"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Voltage",
                "unique": "sunsynk_battery_voltage",
                "category": Category.BATTERY_INFORMATION,
                "register": ["183"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery SOC",
                "unique": "sunsynk_battery_soc",
                "category": Category.BATTERY_INFORMATION,
                "register": ["184"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "device_class": SensorDeviceClass.BATTERY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_185",
                "register": ["185"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "PV1 Power",
                "unique": "sunsynk_pv1_power",
                "category": Category.PV_INFORMATION,
                "register": ["186"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV2 Power",
                "unique": "sunsynk_pv2_power",
                "category": Category.PV_INFORMATION,
                "register": ["187"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "PV3 Power",
                "unique": "sunsynk_pv3_power",
                "category": Category.PV_INFORMATION,
                "register": ["188"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_189",
                "register": ["189"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Battery Power",
                "unique": "sunsynk_battery_power",
                "category": Category.BATTERY_INFORMATION,
                "register": ["190"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "data_type": "S16",
            },
            {
                "name": "Battery Current",
                "unique": "sunsynk_battery_current",
                "category": Category.BATTERY_INFORMATION,
                "register": ["191"],
                "multiplier": -0.01,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "data_type": "S16",
            },
            {
                "name": "Load Frequency",
                "unique": "sunsynk_load_frequency",
                "category": Category.LOAD_INFORMATION,
                "register": ["192"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Inverter Frequency",
                "unique": "sunsynk_inverter_frequency",
                "category": Category.AC_INFORMATION,
                "register": ["193"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Grid Connected",
                "unique": "sunsynk_grid_connected",
                "category": Category.AC_INFORMATION,
                "register": ["194"],
                "multiplier": 0,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_195",
                "register": ["195"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "AUX Frequency",
                "unique": "sunsynk_aux_frequency",
                "category": Category.GENERATOR_INFORMATION,
                "register": ["196"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # BMS / Extended battery registers (314-315)
    # -------------------------------------------------------------------------
    {
        "register_start": 314,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "input",
        "entities": [
            {
                "name": "Battery Charge Limit Current",
                "unique": "sunsynk_battery_charge_limit_current",
                "category": Category.BATTERY_INFORMATION,
                "register": ["314"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Battery Discharge Limit Current",
                "unique": "sunsynk_battery_discharge_limit_current",
                "category": Category.BATTERY_INFORMATION,
                "register": ["315"],
                "multiplier": -1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },
]

# ---------------------------------------------------------------------------
# HOLDING REGISTER GROUPS (writable settings)
# ---------------------------------------------------------------------------

sunsynk_holding_sensors = [
    # -------------------------------------------------------------------------
    # Rated Power (registers 16-17, 32-bit pair)
    # -------------------------------------------------------------------------
    {
        "register_start": 16,
        "poll_speed": PollSpeed.ONCE,
        "register_type": "holding",
        "entities": [
            {
                "name": "Rated Power",
                "unique": "sunsynk_rated_power",
                "category": Category.BASIC_INFORMATION,
                "register": ["16", "17"],
                "multiplier": 0.1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Inverter Enable (register 43)
    # -------------------------------------------------------------------------
    {
        "register_start": 43,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Inverter Enabled",
                "unique": "sunsynk_inverter_enabled",
                "category": Category.BASIC_SETTING,
                "register": ["43"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 1,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Max Solar Power (register 53)
    # -------------------------------------------------------------------------
    {
        "register_start": 53,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Max Solar Power",
                "unique": "sunsynk_max_solar_power",
                "category": Category.POWER_CONTROL_SETTING,
                "register": ["53"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Battery voltage settings (registers 200-211)
    # -------------------------------------------------------------------------
    {
        "register_start": 200,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Control Mode",
                "unique": "sunsynk_control_mode",
                "category": Category.BASIC_SETTING,
                "register": ["200"],
                "multiplier": 0,
            },
            {
                "name": "Battery Equalization Voltage",
                "unique": "sunsynk_battery_equalization_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["201"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Battery Absorption Voltage",
                "unique": "sunsynk_battery_absorption_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["202"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Battery Float Voltage",
                "unique": "sunsynk_battery_float_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["203"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_204",
                "register": ["204"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_205",
                "register": ["205"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_206",
                "register": ["206"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_207",
                "register": ["207"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_208",
                "register": ["208"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_209",
                "register": ["209"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Battery Max Charge Current",
                "unique": "sunsynk_battery_max_charge_current",
                "category": Category.BATTERY_SETTING,
                "register": ["210"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "editable": True,
                "min": 0,
                "max": 185,
            },
            {
                "name": "Battery Max Discharge Current",
                "unique": "sunsynk_battery_max_discharge_current",
                "category": Category.BATTERY_SETTING,
                "register": ["211"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "editable": True,
                "min": 0,
                "max": 185,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Battery capacity/SOC settings (registers 217-235)
    # -------------------------------------------------------------------------
    {
        "register_start": 217,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Battery Shutdown Capacity",
                "unique": "sunsynk_battery_shutdown_capacity",
                "category": Category.BATTERY_SETTING,
                "register": ["217"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 20,
            },
            {
                "name": "Battery Restart Capacity",
                "unique": "sunsynk_battery_restart_capacity",
                "category": Category.BATTERY_SETTING,
                "register": ["218"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 50,
            },
            {
                "name": "Battery Low Capacity",
                "unique": "sunsynk_battery_low_capacity",
                "category": Category.BATTERY_SETTING,
                "register": ["219"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 50,
            },
            {
                "name": "Battery Shutdown Voltage",
                "unique": "sunsynk_battery_shutdown_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["220"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Battery Restart Voltage",
                "unique": "sunsynk_battery_restart_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["221"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Battery Low Voltage",
                "unique": "sunsynk_battery_low_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["222"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_223",
                "register": ["223"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_224",
                "register": ["224"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_225",
                "register": ["225"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_226",
                "register": ["226"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_227",
                "register": ["227"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_228",
                "register": ["228"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_229",
                "register": ["229"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid Charge Battery Current",
                "unique": "sunsynk_grid_charge_battery_current",
                "category": Category.BATTERY_SETTING,
                "register": ["230"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "editable": True,
                "min": 0,
                "max": 185,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_231",
                "register": ["231"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Grid Charge Enabled",
                "unique": "sunsynk_grid_charge_enabled",
                "category": Category.BATTERY_SETTING,
                "register": ["232"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 1,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_233",
                "register": ["233"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_234",
                "register": ["234"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Generator Input",
                "unique": "sunsynk_generator_input",
                "category": Category.GENERATOR_SETTING,
                "register": ["235"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 2,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # System control (registers 243-248)
    # -------------------------------------------------------------------------
    {
        "register_start": 243,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Priority Load",
                "unique": "sunsynk_priority_load",
                "category": Category.FUNCTIONAL_SETTING,
                "register": ["243"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 1,
            },
            {
                "name": "Load Limit",
                "unique": "sunsynk_load_limit",
                "category": Category.FUNCTIONAL_SETTING,
                "register": ["244"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 2,
            },
            {
                "name": "Max Sell Power",
                "unique": "sunsynk_max_sell_power",
                "category": Category.POWER_CONTROL_SETTING,
                "register": ["245"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "reserve",
                "unique": "sunsynk_reserve_246",
                "register": ["246"],
                "multiplier": 0,
                "hidden": True,
            },
            {
                "name": "Solar Export",
                "unique": "sunsynk_solar_export",
                "category": Category.FUNCTIONAL_SETTING,
                "register": ["247"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 1,
            },
            {
                "name": "Use Timer",
                "unique": "sunsynk_use_timer",
                "category": Category.FUNCTIONAL_SETTING,
                "register": ["248"],
                "multiplier": 0,
                "editable": True,
                "min": 0,
                "max": 1,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Program times (registers 250-255)
    # -------------------------------------------------------------------------
    {
        "register_start": 250,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {"name": "Prog1 Time", "unique": "sunsynk_prog1_time", "category": Category.HYBRID_MODE_SETTING, "register": ["250"], "multiplier": 0},
            {"name": "Prog2 Time", "unique": "sunsynk_prog2_time", "category": Category.HYBRID_MODE_SETTING, "register": ["251"], "multiplier": 0},
            {"name": "Prog3 Time", "unique": "sunsynk_prog3_time", "category": Category.HYBRID_MODE_SETTING, "register": ["252"], "multiplier": 0},
            {"name": "Prog4 Time", "unique": "sunsynk_prog4_time", "category": Category.HYBRID_MODE_SETTING, "register": ["253"], "multiplier": 0},
            {"name": "Prog5 Time", "unique": "sunsynk_prog5_time", "category": Category.HYBRID_MODE_SETTING, "register": ["254"], "multiplier": 0},
            {"name": "Prog6 Time", "unique": "sunsynk_prog6_time", "category": Category.HYBRID_MODE_SETTING, "register": ["255"], "multiplier": 0},
        ],
    },

    # -------------------------------------------------------------------------
    # Program power limits (registers 256-261)
    # -------------------------------------------------------------------------
    {
        "register_start": 256,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Prog1 Power",
                "unique": "sunsynk_prog1_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["256"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "Prog2 Power",
                "unique": "sunsynk_prog2_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["257"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "Prog3 Power",
                "unique": "sunsynk_prog3_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["258"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "Prog4 Power",
                "unique": "sunsynk_prog4_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["259"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "Prog5 Power",
                "unique": "sunsynk_prog5_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["260"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
            {
                "name": "Prog6 Power",
                "unique": "sunsynk_prog6_power",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["261"],
                "multiplier": 1,
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "editable": True,
                "min": 0,
                "max": 5000,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Program voltages (registers 262-267)
    # -------------------------------------------------------------------------
    {
        "register_start": 262,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Prog1 Voltage",
                "unique": "sunsynk_prog1_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["262"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Prog2 Voltage",
                "unique": "sunsynk_prog2_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["263"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Prog3 Voltage",
                "unique": "sunsynk_prog3_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["264"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Prog4 Voltage",
                "unique": "sunsynk_prog4_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["265"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Prog5 Voltage",
                "unique": "sunsynk_prog5_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["266"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
            {
                "name": "Prog6 Voltage",
                "unique": "sunsynk_prog6_voltage",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["267"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "editable": True,
                "min": 41,
                "max": 60,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # Program capacities + charge/mode (registers 268-279)
    # -------------------------------------------------------------------------
    {
        "register_start": 268,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Prog1 Capacity",
                "unique": "sunsynk_prog1_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["268"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {
                "name": "Prog2 Capacity",
                "unique": "sunsynk_prog2_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["269"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {
                "name": "Prog3 Capacity",
                "unique": "sunsynk_prog3_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["270"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {
                "name": "Prog4 Capacity",
                "unique": "sunsynk_prog4_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["271"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {
                "name": "Prog5 Capacity",
                "unique": "sunsynk_prog5_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["272"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {
                "name": "Prog6 Capacity",
                "unique": "sunsynk_prog6_capacity",
                "category": Category.HYBRID_MODE_SETTING,
                "register": ["273"],
                "multiplier": 1,
                "unit_of_measurement": PERCENTAGE,
                "editable": True,
                "min": 0,
                "max": 100,
            },
            {"name": "Prog1 Charge", "unique": "sunsynk_prog1_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["274"], "multiplier": 0},
            {"name": "Prog2 Charge", "unique": "sunsynk_prog2_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["275"], "multiplier": 0},
            {"name": "Prog3 Charge", "unique": "sunsynk_prog3_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["276"], "multiplier": 0},
            {"name": "Prog4 Charge", "unique": "sunsynk_prog4_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["277"], "multiplier": 0},
            {"name": "Prog5 Charge", "unique": "sunsynk_prog5_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["278"], "multiplier": 0},
            {"name": "Prog6 Charge", "unique": "sunsynk_prog6_charge", "category": Category.HYBRID_MODE_SETTING, "register": ["279"], "multiplier": 0},
        ],
    },

    # -------------------------------------------------------------------------
    # Battery charging voltage (register 312), limits (314-315) isolated
    # -------------------------------------------------------------------------
    {
        "register_start": 312,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "Battery Charging Voltage",
                "unique": "sunsynk_battery_charging_voltage",
                "category": Category.BATTERY_SETTING,
                "register": ["312"],
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # BMS Protocol (register 325)
    # -------------------------------------------------------------------------
    {
        "register_start": 325,
        "poll_speed": PollSpeed.SLOW,
        "register_type": "holding",
        "entities": [
            {
                "name": "BMS Protocol",
                "unique": "sunsynk_bms_protocol",
                "category": Category.BATTERY_SETTING,
                "register": ["325"],
                "multiplier": 0,
            },
        ],
    },
]

# Combined list for the __init__.py setup
sunsynk_single_phase_sensors = sunsynk_input_sensors + sunsynk_holding_sensors
sunsynk_single_phase_sensors_derived = []
